### PR TITLE
Processing System Properties thread safely.

### LINKED ISSUE #2605: Failed to load environment variables: java.util.ConcurrentModificationException
`io.hawt.blueprint.HawtioBlueprintContextListener.appendEnvironmentVariablesAndSystemProperties` iterates over system properties [here](https://github.com/hawtio/hawtio/blob/master/hawtio-base/src/main/java/io/hawt/blueprint/HawtioBlueprintContextListener.java#L106)

In case properties are programatically modified there is a race condition leading to ConcurrentModificationException below.
This is the same and can be fixed in the same manner like [KARAF-6337](https://issues.apache.org/jira/browse/KARAF-6337)

```
Failed to load environment variables:
java.util.ConcurrentModificationException
java.util.ConcurrentModificationException: null
	at java.util.Hashtable$Enumerator.next(Hashtable.java:1387) ~[?:?]
	at io.hawt.blueprint.HawtioBlueprintContextListener.appendEnvironmentVariablesAndSystemProperties(HawtioBlueprintContextListener.java:106) ~[663:io.hawt.hawtio-war:2.7.1]
	at io.hawt.blueprint.HawtioBlueprintContextListener.contextInitialized(HawtioBlueprintContextListener.java:93) ~[663:io.hawt.hawtio-war:2.7.1]
```

### PR DESCRIPTION
**Pull request by MrEasy**
fixes #2605

### CODE REVIEW

File: hawtio-base/src/main/java/io/hawt/blueprint/HawtioBlueprintContextListener.java [hunk 1]
```diff
@@ -102,18 +102,17 @@ public int compare(URL o1, URL o2) {
...
-                    String propertyValue = value.toString();
-                    if (!properties.containsKey(propertyName)) {
+            // iterating over sysProps.keySet() directly is not thread-safe and may throw ConcurrentMod.Ex.,
+            // so first get the keys and then query their values
+            Set<String> keys = sysProperties.stringPropertyNames();
+            for (String propertyName : keys) {
+                String propertyValue = sysProperties.getProperty(propertyName); // value can be null if removed in meantime, but unlikely
+                if (propertyName != null && propertyValue != null &&
+                    !properties.containsKey(propertyName)) {
                         properties.put(propertyName, propertyValue);
```
Comment (MrEasy) [inline hawtio-base/src/main/java/io/hawt/blueprint/HawtioBlueprintContextListener.java]: This could be simplified into `properties.putIfAbsent(propertyName, propertyValue);` with the small logical difference, that an existing mapping key-null would not ne overwritten. Not the case in any case, but did not want to change the logic.

**Comment by tadayosi** [comment]
@MrEasy Sorry for not noticing this earlier, and thanks for your contribution!
